spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

api.key: bbdbca8e-67a0-43a0-82d7-41363541ea4b
spotify.client.id: some-client-id
spotify.client.secret: some-client-secret

---
spring:
  config:
    activate:
      on-profile: local
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    password: secret
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser

